ims/ims/addons/scanner/urls.py
from django.urls import re_path
from ims.addons.scanner import views

app_name='ims.addons.scanner'
urlpatterns = [
    re_path(r'create/$', views.create, name='create'),
    re_path(r'scan/$', views.scan, name='scan'),
    re_path(r'scanned/(?P<qrcode>[\.\-_\=\w\s]+)$', views.scanned, name='scanned'),
    re_path(r'ajax/$', views.ajax, name='ajax_call'),
    re_path(r'ajax_create/$', views.ajax_create, name='ajax_create'),
    re_path(r'$', views.home, name='home'),
]

ims/ims/addons/scanner/forms.py
from django import forms
from inventory.models import Part


MODEL_CHOICES =(
    ("part","Part"),
    ("assembly","Assembly"),
    ("storage","Storage"),
    ("partstorage","PartStorage"),
    ("kit","Kit"),
)

ACTION_CHOICES =(
    ("add","Add"),
    ("sub","Subtract"),
    ("get","Get"),
)

# Idea to have search functionality to field 't' that does API queries with 'starts with' to the selected 'm'

class ModelGenerateForm(forms.Form):
    m = forms.ChoiceField(choices=MODEL_CHOICES)
    t = forms.ModelChoiceField(queryset=Part.objects.all().exclude(name='deleted'), empty_label="---------", to_field_name="name")
    d = forms.ChoiceField(choices=ACTION_CHOICES)
    n = forms.IntegerField(min_value=0,initial=0)
    c = forms.BooleanField(required=False)

ims/ims/addons/scanner/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.http import HttpResponseForbidden, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from json import loads
import logging
import requests

from inventory.models import Part, Storage, PartStorage, Assembly, Kit
from ims.addons.scanner.forms import ModelGenerateForm
from log.logger import getLogger
import ims.addons.scanner.helpers as helpers

logger = logging.getLogger(__name__)
logger2 = getLogger('scanner')

# Make this into a nice ajax call
@permission_required('scanner.add_qrcode')
def create(request):
    logger.debug('Request made to create view')
    generate_form = ModelGenerateForm()
    logger2.info(request.user, 'Accessed Create page')
    return render(request, 'scanner/create.html', {'generate_form': generate_form})

def ajax_create(request):
    logger.debug('Request made to ajax_create view')
    logger2.debug((request.user or 0), 'Request to view ajax_create page')
    if not request.user.has_perm('scanner.add_qrcode'):
        logger.info('HttpResponseForbidden response for ajax_create view')
        logger2.warning((request.user or 0), 'Unauthorized request to path {}'.format(request.path))
        return HttpResponseForbidden()
    action = 'go'
    model = request.GET.get('m')
    display = request.GET.get('c')
    caption = url = ''
    if model == 'assembly':
        logger.debug('Model is Assembly, attempting to locate the target')
        target = request.GET.get('t')
        assembly = Assembly.objects.filter(parent__name=target)[0]
        url = request.build_absolute_uri(assembly.get_absolute_url())
        logger.debug('Found absolute URI')
    if model == 'part':
        logger.debug('Model is Part, attempting to locate the target')
        target = request.GET.get('t')
        part = get_object_or_404(Part, name=target)
        url = request.build_absolute_uri(part.get_absolute_url())
        logger.debug('Found absolute URI')
    if model == 'storage':
        logger.debug('Model is Storage, attempting to locate the target')
        target = request.GET.get('t')
        storage = get_object_or_404(Storage, name=target)
        url = request.build_absolute_uri(storage.get_absolute_url())
        logger.debug('Found absolute URI')
    if model == 'partstorage':
        logger.debug('Model is PartStorage, attempting to locate the target')
        target = request.GET.get('t')
        part = helpers.find_part(target)
        storage = helpers.find_storage(target)
        logger.debug('Getting direction and increment from request data')
        direction = request.GET.get('d')
        if direction == 'get':
            logger.info('Invalid Action selected for partstorage create qrcode request')
            logger2.info(request.user, 'Invalid Action selected for partstorage create qrcode request')
            return HttpResponseBadRequest()
        increment = request.GET.get('n')
        ps = get_object_or_404(PartStorage, part=part, storage=storage)
        url = request.build_absolute_uri('/api/v1/inventory/partstorage/{}/{}/{}/'.format(ps.id, direction, increment))
        logger.debug('Found absolute URI')
        action = 'do'
    if model == 'kit':
        logger.debug('Model is Kit, attempting to locate the target')
        target = request.GET.get('t')
        kit = get_object_or_404(Kit, name=target)
        direction = request.GET.get('d')
        if direction == 'get':
            url = request.build_absolute_uri(kit.get_absolute_url())
        elif direction == 'sub':
            action = 'do'
            increment = request.GET.get('n')
            url = request.build_absolute_uri('/api/v1/inventory/kit/{}/sub/{}/'.format(kit.id, increment))
        logger.debug('Found absolute URI')
    if url == '':
        return HttpResponseBadRequest()
    url = url.replace('http://', 'https://')
    logger.debug('Generating the QR Code')
    qrimage = helpers.generate(target, url, action)
    logger.debug('Generating Caption')
    if model == 'kit':
        if direction == 'get':
            caption = '{} - {}'.format(model, target)
        else:
            caption = '{} - {} - {}:{}'.format(model, target, direction, increment)
    elif model == 'partstorage':
        caption = '{} - {} - {}:{}'.format(model, target, direction, increment)
    else:
        caption = '{} - {}'.format(model, target)
    logger.debug('Rendering request for create view')
    logger2.info(request.user, 'Accessed generated QR code for {}'.format(caption))
    if display == 'true':
        return render(request, 'scanner/code.html', {'qrimage': qrimage, 'caption': caption})
    return render(request, 'scanner/code.html', {'qrimage': qrimage, 'caption': ''})

def home(request):
    logger.debug('Request made to home view')
    logger2.debug((request.user or 0), 'Request to view Home page')
    if request.user.is_authenticated:
        logger.debug('Rendering request for home view')
        logger2.info((request.user or 0), 'Accessed Home page')
        return render(request, 'scanner/home.html')
    else:
        logger.debug('User was not authenticated')
        logger2.warning(0, 'Unauthenticated request to {}'.format(request.path))
        return redirect('/accounts/login/?next={}'.format(request.path))

def scan(request):
    logger.debug('Request made to scan view')
    logger2.debug((request.user or 0), 'Request to view Scan page')
    if request.user.is_authenticated:
        logger.debug('Rendering request for scan view')
        logger2.info(request.user, 'Accessed Scan page')
        return render(request, 'scanner/scan.html')
    else:
        logger.debug('User was not authenticated and ALLOW_ANONYMOUS is set to False')
        logger2.warning(0, 'Unauthenticated request to {}'.format(request.path))
        return redirect('/accounts/login/?next={}'.format(request.path))

def scanned(request, qrcode):
    logger.debug('Request made to scanned view')
    logger2.debug((request.user or 0), 'Request to parse Scan')
    if request.user.is_authenticated:
        data = helpers.decode(qrcode)
        if data == '':
            logger.debug('Redirecting request to scan view')
            logger2.debug(request.user, 'Empty data, redirecting to Scan page')
            return redirect('/scanner/scan/')
        if helpers.compare_token(data):
            logger.debug('Data token and new hash matched')
            if data['action'] == 'go':
                logger.debug('Data action is "go"')
                if request.user.has_perm('scanner.view_qrcode'):
                    logger.debug('Redirecting request to "{}"'.format(data['url']))
                    logger2.info(request.user, 'Scanned code and redirecting to "{}"'.format(data['url']))
                    return redirect(data['url'])
                logger.debug('Unauthorized request to view scanned url "{}"'.format(data['url']))
                logger2.debug(request.user, 'Unauthorized request to view scanned url "{}"'.format(data['url']))
                return redirect('/scanner/scan/')
            if data['action'] == 'do':
                logger.debug('Data action is "do"')
                if request.user.has_perm('scanner.change_qrcode'):
                    logger.debug('Making request to "' + data['url'] + '"')
                    result = requests.request('GET', data['url'])
                    json = loads(result.text)
                    logger.debug('Loaded the results and rendering the request for scanned view')
                    logger2.info(request.user, 'Scanned code and performed action with result "{}"'.format(json['message']))
                    return render(request, 'scanner/result.html', {'message': json['message'], 'current_count': json['partstorage']['count']})
                logger.debug('Unauthorized request to execute scanned url "{}"'.format(data['url']))
                logger2.debug(request.user, 'Unauthorized request to execute scanned url "{}"'.format(data['url']))
                return redirect('/scanner/scan/')
        logger.debug('Redirecting request to scan view')
        logger2.debug(request.user, 'Token and Hash mismatch, redirecting to Scan page')
        return redirect('/scanner/scan/')
    logger.debug('User was not authenticated and ALLOW_ANONYMOUS is set to False')
    logger2.warning(0, 'Unauthenticated request to {}'.format(request.path))
    return redirect('/accounts/login/?next={}'.format(request.path))

def ajax(request):
    logger.debug('Request made to ajax view')
    logger2.debug((request.user or 0), 'Request to ajax view')
    if request.user.has_perm('scanner.add_qrcode'):
        items = []
        selected = request.GET.get('selected')
        if selected == 'assembly':
            logger.debug('Generating a list of Assembly objects')
            # Get all Assemblies
            objects = list(set(Assembly.objects.values_list('parent', flat=True)))
            items = Part.objects.filter(pk__in=objects)
            if not settings.SHOW_DELETED_OBJECTS:
                items = items.exclude(name='deleted')
        if selected == 'part':
            logger.debug('Generating a list of Part objects')
            # Get all Parts
            items = Part.objects.all()
            if not settings.SHOW_DELETED_OBJECTS:
                items = items.exclude(name='deleted')
        if selected == 'storage':
            logger.debug('Generating a list of Storage objects')
            # Get all Storage
            items = Storage.objects.all()
            if not settings.SHOW_DELETED_OBJECTS:
                items = items.exclude(name='deleted')
        if selected == 'partstorage':
            logger.debug('Generating a list of PartStorage objects')
            # Get all PartStorage
            items = PartStorage.objects.all()
            if not settings.SHOW_DELETED_OBJECTS:

ims/templates/scanner/code.html
<img src="{{ qrimage }}" class="w3-image" />
<p>{{ caption }}</p>

ims/templates/scanner/create.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% load static %}
{% block title %}Generate QR Code{% endblock %}
{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Generate QR Code</b></h4>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="get">
            {{ generate_form.non_field_errors }}
            {% for field in generate_form %}
            {% if field.name in "m,t" %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% elif field.name in "c" %}
            <div class="w3-bar-item">
                {{ field.errors }}
                <div class="w3-left ims-select-options ims-form-field">
                    {{ field }}
                    <label for="id_c" class="ims-select-options">Include Caption</label>
                </div>
            </div>
            {% else %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field ims-hidden" }}
            </div>
            {% endif %}
            {% endfor %}
            <div class="w3-bar-item">
                <a href="javascript:void(0)" onclick="generatecode()" class="w3-button w3-dark-grey ims-form-field">Generate</a>
            </div>
        </form>
    </div>
    <div class="w3-container ims-hidden" id="print_area">
        <div class="w3-col l12 xl6 w3-card w3-padding">
            <div id="print_content">
                <img src="{{ qrimage }}" class="w3-image" />
                <p>{{ caption }}</p>
            </div>
            <div id="print_button">
                <a class="w3-button w3-light-gray w3-padding-large w3-margin-top" onclick="opentoprint()">Print</a>
                <a class="w3-button w3-dark-gray w3-padding-large w3-margin-top" onclick="clearprintarea()">Clear</a>
            </div>
        </div>
    </div>
</div>
<script src="{% static "common/js/jquery.min.js" %}"></script>
<script>
    $("#id_m").change(function () {
        var selectedId = $(this).val();
        $.ajax({
            url: '/scanner/ajax/',
            data: {
                'selected': selectedId
            },
            success: function (data) {
                $("#id_t").html(data);
            }
        });
        if (selectedId == 'partstorage' || selectedId == 'kit') {
            var element = document.getElementById("id_d");
            element.classList.remove('ims-hidden');
            var element = document.getElementById("id_n");
            element.classList.remove('ims-hidden');
	    }
        else {
            var element = document.getElementById("id_d");
            element.classList.add('ims-hidden');
            var element = document.getElementById("id_n");
            element.classList.add('ims-hidden');
        }
    });
    function generatecode() {
        var e = document.getElementById('id_m');
        var model = e.options[e.selectedIndex].value;
        var e = document.getElementById('id_t');
        var target = e.options[e.selectedIndex].value;
        var e = document.getElementById('id_d');
        var direction = e.options[e.selectedIndex].value;
        var num = document.getElementById('id_n').value;
        var caption = $('#id_c').is(":checked");
        $.ajax({
            url: '/scanner/ajax_create/?m='+model+'&t='+target+'&d='+direction+'&n='+num+'&c='+caption,
            type: 'get',
            success: function(data) {
                $("#print_content").html(data);
                document.getElementById("print_area").classList.remove('ims-hidden');
            },
            error: function() {
                clearprintarea();
            }
        });
    }
    function clearprintarea(){
        document.getElementById("print_area").classList.add('ims-hidden');
        document.getElementById("print_content").innerHTML = "";
    }
    function opentoprint() {
        var qrimage = document.getElementById("print_content").innerHTML;
    
        var docprint= window.open('','','toolbar=yes,location=no,directories=yes,menubar=yes,scrollbars=yes,width=415,height=415,left=100,top=25');
        docprint.document.open();
        docprint.document.write('<html><head><title>Print QR Code</title></head><body onLoad="self.print()">');
        docprint.document.write(qrimage);
        docprint.document.write('</body></html>');
        docprint.document.close();
        docprint.focus();
    }
</script>
{% endblock %}

ims/templates/scanner/dropdown_list_options.html
<option value="">---------</option>
{% for item in items %}
<option value="{{ item }}">{{ item }}</option>
{% endfor %}

ims/templates/scanner/home.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}QR Code{% endblock %}
{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Scanner Module</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col l12 xl6 w3-card w3-padding w3-bar-block">
            <div class="w3-bar-item">
                <a class="w3-button ims-form-field" href="/scanner/scan/">Scan</a>
            </div>
            <div class="w3-bar-item">
                <a class="w3-button w3-dark-gray ims-form-field" href="/scanner/create/">Create</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ims/templates/scanner/result.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Scan Results{% endblock %}
{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Scan Results</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-margin w3-padding">
            <span><em>{{ message }}</em></span><br/>
	    {% if current_count %}
	    <span>The current count is: <b>{{ current_count }}</b></span>
	    {% endif %}
        <div class="w3-margin w3-padding">
            <a class="w3-button ims-form-field" href="/scanner/scan/">Scan Again</a>
        </div>
    </div>
</div>
{% endblock %}

ims/templates/scanner/scan.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% load static %}
{% block title %}Scan QR Code{% endblock %}
{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Scan QR Code</b></h4>
    </div>
    <div class="w3-container">
        <div>
            <video id="qr-video" class="ims-hidden"></video>
        </div>
    </div>
</div>
<script type="module">
    import QrScanner from "{% static "scanner/js/qr-scanner.min.js" %}";
    QrScanner.WORKER_PATH = "{% static "scanner/js/qr-scanner-worker.min.js" %}";

    const video = document.getElementById('qr-video');
    const camQrResult = document.getElementById('cam-qr-result');

    function setResult(result) {
        scanner.stop();
	scanner.destroy();
	window.location.assign('/scanner/scanned/qrcode=' + result);
    }

    const scanner = new QrScanner(video, result => setResult(result));
    video.parentNode.insertBefore(scanner.$canvas, null);
    scanner.$canvas.style.display = 'block';
    scanner.$canvas.style.maxWidth = "100%";

    scanner.start()

    window.scanner = scanner;

</script>
{% endblock %}